all:
	python3.6 run_assignment1.py --input_path 'assignment_1_data/input.json' --solution_path 'solution.json'
	python3.6 error_check.py --ground_truth_path 'assignment_1_data/output.json' --solution_path 'solution.json' --error_path 'error_list.json'